// Define the exchange rate
export const USD_TO_UGX_RATE = 3500

export type Project = {
  id: number
  slug: string
  name: string
  location: string
  description: string
  longDescription: string
  budget: number
  raised: number
  images: string[]
  videos: string[]
  budgetPhases?: {
    phaseName: string
    amountUSD: number
  }[]
  accounting?: {
    date: string
    description: string
    amount: number
    receiptUrl: string
  }[]
}

export type Donation = {
  id: number
  donorName: string
  amount: number
  date: string
  projectId: number | null // projectId can be null for general donations
}

// -- PROJECTS_START --
// This section is automatically generated by the script. Do not edit manually.
export const projects: Project[] = [
  {
    id: 1,
    slug: "ageri-mosque",
    name: "Ageri Mosque Construction",
    location: "Ageri Village, Uganda",
    description: "Help us build a permanent, safe, and beautiful mosque for the community of Ageri.",
    longDescription:
      "The Ageri community currently prays in a temporary structure that is exposed to the elements. This project aims to construct a durable mosque that can accommodate over 200 worshippers, providing a dedicated space for prayers, community gatherings, and Islamic education for children.",
    budget: 60000,
    raised: 12500,
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    videos: ["https://www.youtube.com/embed/dQw4w9WgXcQ"],
    budgetPhases: [
      { phaseName: "Phase 1: Foundation & Land Prep", amountUSD: 15000 },
      { phaseName: "Phase 2: Walls, Columns & Roofing", amountUSD: 25000 },
      { phaseName: "Phase 3: Finishing (Plaster, Paint, Windows)", amountUSD: 12000 },
      { phaseName: "Phase 4: Wudu Area & Facilities", amountUSD: 8000 },
    ],
  },
  {
    id: 2,
    slug: "hidayah-mosque",
    name: "Hidayah Mosque Expansion",
    location: "Hidayah Town, Uganda",
    description: "Expanding the Hidayah Mosque to accommodate the growing Muslim population.",
    longDescription:
      "The Hidayah Mosque has been a central pillar of the community for years, but it's now too small for the growing number of attendees, especially during Friday prayers. This project will expand the main prayer hall, add new wudu (ablution) facilities, and construct classrooms for a new madrasa.",
    budget: 75000,
    raised: 45000,
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    videos: ["https://www.youtube.com/embed/dQw4w9WgXcQ"],
    budgetPhases: [
      { phaseName: "Phase 1: Expansion Foundation", amountUSD: 20000 },
      { phaseName: "Phase 2: Main Hall Extension", amountUSD: 35000 },
      { phaseName: "Phase 3: New Wudu Facilities", amountUSD: 10000 },
      { phaseName: "Phase 4: Madrasa Classrooms", amountUSD: 10000 },
    ],
  },
]
// -- PROJECTS_END --

// The donations array is now fetched from the database via app/donations/actions.ts
// export const donations: Donation[] = [...]

export const getTotalRaised = () => projects.reduce((acc, p) => acc + p.raised, 0)
export const getTotalBudget = () => projects.reduce((acc, p) => acc + p.budget, 0)
